swagger: "2.0"
info:
  title: Factory Management System API
  description: API documentation for managing factory operations.
  version: "1.0.0"
paths:
  /customers:
    post:
      summary: Create a new customer
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              phone:
                type: string
      responses:
        201:
          description: Customer created successfully
        400:
          description: Invalid input
        500:
          description: Server error
    get:
      summary: Get all customers
      responses:
        200:
          description: A list of customers
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
  /employees:
    post:
      summary: Create a new employee
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              position:
                type: string
      responses:
        201:
          description: Employee created successfully
    get:
      summary: Get all employees
      responses:
        200:
          description: A list of employees
  /orders:
    post:
      summary: Create a new order
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              customer_id:
                type: integer
              product_id:
                type: integer
              quantity:
                type: integer
      responses:
        201:
          description: Order created successfully
    get:
      summary: Get all orders
      responses:
        200:
          description: A list of orders
  /products:
    post:
      summary: Create a new product
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              price:
                type: number
      responses:
        201:
          description: Product created successfully
    get:
      summary: Get all products
      responses:
        200:
          description: A list of products
  /production:
    post:
      summary: Record new production
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              product_id:
                type: integer
              quantity_produced:
                type: integer
              date_produced:
                type: string
                format: date
      responses:
        201:
          description: Production recorded successfully
    get:
      summary: Get all production records
      responses:
        200:
          description: A list of production records
